Добавление БД.
the8nd/avitoparser pull request #4
Opened 2023-02-11 20:22 UTC by the8nd

Для запуска цикла проверки ссылок надо ввести /start. Оставил print в all_msg для проверки.

2023-02-12 16:51 UTC, the8nd commented
Функция urls_check сейчас запускается при получении команды /start и крутится бесконечно. Это немного не правильно, т.к при перезагрузке бота нужно заново отправлять /start, так же если 2 человека это сделают, то объявления будут дублироваться, если у них одинаковые URL указаны. Я пробовал через asyncio.run запускать ее, но получал ошибку связанную с event loop. Пока решения я не придумал.

2023-02-14 13:06 UTC, the8nd commented
loop = asyncio.get_event_loop()
loop.run_until_complete(func)
Возможно это поможет. Попробую сегодня проверить.

2023-02-15 06:39 UTC, avdeenkodmitry commented on main.py
> +engine = db.create_engine('sqlite:///urls_base.db')
Давай вынесем всю логику по работе с базой данных в отдельный файл

2023-02-15 07:01 UTC, avdeenkodmitry requested changes

2023-02-15 07:01 UTC, avdeenkodmitry commented on main.py
> +async def urls_check():
очень большая функция. Давай часть по работе с базой вынесем в отдельные функции

2023-02-15 07:01 UTC, avdeenkodmitry commented on main.py
> +                pass
надо залогировать, почему произошел эксепшен

2023-02-15 07:01 UTC, avdeenkodmitry commented on main.py
> +                     db.Column('last_urls', db.Text),
мы можем хранить, например, json field https://www.sqlite.org/json1.html

2023-02-15 08:15 UTC, the8nd commented on main.py
> +                     db.Column('last_urls', db.Text),
last_urls или это про вcю таблицу?

2023-02-15 16:02 UTC, the8nd commented on main.py
> +                pass
Она выскакивает при добавлении новой ссылки, у которой еще нет last urls, а код пытается .split() сделать в результате чего и получает ошибку. Нужно ли логирование для этого?

2023-02-24 13:02 UTC, avdeenkodmitry commented on avdbfuncs.py
> +engine = db.create_engine('sqlite:///urls_base.db')
Такие данные должны содержаться в конфиге (в отдельном модуле). Можем пока так оставить, потом перенесем.

2023-02-24 13:02 UTC, avdeenkodmitry commented on avdbfuncs.py
> +    url_check = db.select(urls_base.columns.url_name, urls_base.columns.url, urls_base.columns.last_urls, urls_base.columns.url_id).where(urls_base.columns.status == True, urls_base.columns.user_id =
очень длинная строка :)

2023-02-24 13:06 UTC, avdeenkodmitry commented on avdbfuncs.py
> +                counter += 1
Но надо протестить код
```suggestion
            last_links = '\m/'.join([url_avcheck[0][counter] for counter in range(3)])
```

2023-02-24 13:08 UTC, avdeenkodmitry commented on avdbfuncs.py
> +    msg_to_return = msg_to_return + hlink(data[0][4], data[0][3])
тоже давай перепишем через `join` функцию

2023-02-24 13:10 UTC, avdeenkodmitry commented on avdbfuncs.py
> +    msg_to_return = msg_to_return + hlink(data[0][4], data[0][3])
еще ты точно уверен, что data[][] элементы всегда существуют? Может быть тут keyerror  нужно ловить?

2023-02-24 13:11 UTC, avdeenkodmitry commented on avdbfuncs.py
> +            counter += 1
тоже через join

2023-02-24 13:11 UTC, the8nd commented on avdbfuncs.py
> +    msg_to_return = msg_to_return + hlink(data[0][4], data[0][3])
Должны всегда существовать. Но добавлю try, except на всякий случай

2023-02-24 13:11 UTC, avdeenkodmitry commented on avdbfuncs.py
> +            counter += 1
вообще этот код встречается несколько раз

2023-02-25 13:46 UTC, merged